### ISSUE TITLE
CTRexClient.is_running() errors out

### ISSUE THREAD

**Issue by ghost** [cisco-system-traffic-generator/trex-core#76]
Hi
Thanks for creating the best opensource traffic generator. I am just trying to connect to a trex server and get its status. It worked fine with v2.30 and is failing with v2.34. Any ideas?

```
pharidos@uks2:~/trex/trex_client_v2.34/$ PYTHONPATH=stl/:stf/ python
Python 2.7.14 (default, Sep 17 2017, 18:50:44)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from trex_stf_lib.trex_client import CTRexClient
>>> trex_server=CTRexClient('10.156.34.208')
>>> trex_server.is_running()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 426, in is_running
    res = self.get_running_info()
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 548, in get_running_info
    self.result_obj.update_result_data(latest_dump)
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 1518, in update_result_data
    self._avg_latency        = CTRexResult.__avg_all_and_rename_keys(avg_latency)
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 1601, in __avg_all_and_rename_keys
    all_list  = src_dict.values()
AttributeError: 'NoneType' object has no attribute 'values'
```

```
>>> print trex_server.result_obj.get_last_value("trex-latency.data", "avg-")
None
>>>
>>> print trex_server.result_obj
Is valid history?       True
Done warmup?            False
Expected tx rate:       {u'm_tx_expected_pps': 0.0, u'm_tx_expected_bps': 0.0, u'm_tx_expected_cps': 0.0}
Current tx rate:        {u'm_tx_bps': 0.0, u'm_tx_cps': 0.0, u'm_tx_pps': 0.0}
Minimum latency:        {}
Maximum latency:        {}
Average latency:        None
Average window latency: None
Total drops:            None
Drop rate:              None
History size so far:    1
```

**Comment by ybrustin** [comment]
Hi,

Did you run the TRex server with any mode ( stateful / stateless / astf ) ?
Can you recreate this error? If so, please print the latest_dump before this line:
`self.result_obj.update_result_data(latest_dump)`

**Comment by hprem** [comment]
Trex is started in stateless mode using the cli
```
/usr/local/share/trex//_t-rex-64 --iom 0 -i --no-key
```

And this is how looks `latest_dump` looks  like when I see the failure for the first time
```
{u'trex-global': {u'type': 0, u'data': {u'm_cpu_util_raw': 4.0, u'm_total_nat_learn_error': 0, u'm_total_tx_bps-0': 15793666.0, u'm_total_tx_bps-1': 15793917.0, u'm_cpu_util': 2.64, u'm_total_alloc_error': 0, u'm_active_flows': 0.0, u'm_
total_servers': 0, u'm_total_rx_bps-1': 26962898.0, u'm_platform_factor': 1.0, u'm_rx_drop_bps': 0.0, u'm_total_nat_time_out': 0, u'm_tx_expected_bps': 0.0, u'm_total_clients': 0, u'm_socket_util': 0.0, u'unknown': 0, u'ts': {u'freq': 25
96991324, u'value': 425349401064}, u'ierrors-0': 0, u'ierrors-1': 0, u'opackets-1': 549777, u'opackets-0': 549750, u'm_rx_pps': 58110.9, u'template': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0], u'm_total_rx_bytes': 127545132, u'm_total_rx_pkts': 1099527, u'm_total_tx_pkts': 1099527, u'm_total_nat_active': 0, u'm_total_nat_syn_wait': 0, u'oerrors-0': 0, u'oerrors-1': 0, u'm_rx_bps': 53926956.0, u'm_total_queue_full':
0, u'm_total_rx_pps-0': 29056.1, u'm_total_rx_pps-1': 29054.8, u'm_open_flows': 0.0, u'm_tx_expected_pps': 0.0, u'm_rx_cpu_util': 0.2274, u'm_total_nat_no_fid': 0, u'm_total_tx_pps-1': 29032.9, u'm_cpu_util-0': 0.0, u'm_total_queue_drop'
: 0, u'm_active_sockets': 0, u'm_rx_core_pps': 58110.1, u'm_tx_bps': 31587582.0, u'm_total_rx_bps-0': 26964056.0, u'm_tx_pps': 58065.4, u'm_total_nat_open': 0, u'm_total_tx_pps-0': 29032.5, u'm_tx_cps': 0.0, u'm_bw_per_core': 2.393, u'm_
total_tx_bytes': 74767836, u'ibytes-1': 63774132, u'ibytes-0': 63771000, u'm_total_nat_time_out_wait_ack': 0, u'm_cpu_util-1': 0.0, u'ipackets-1': 549777, u'ipackets-0': 549750, u'obytes-1': 37384836, u'obytes-0': 37383000, u'm_tx_expect
ed_cps': 0.0}, u'name': u'trex-global'}, u'tx-gen': {u'type': 0, u'data': {u'realtime-hist': {u'cnt': 0, u'max_usec': 0, u'min_usec': 10, u'high_cnt': 0, u's_avg': 0.0, u'histogram': []}, u'unknown': 0}, u'name': u'tx-gen'}, u'trex-event
': {u'data': {u'who': u'pharidos', u'port_id': 1, u'session_id': 6557788}, u'type': 6, u'name': u'trex-event'}, u'trex-barrier': {u'data': {}, u'type': 2485789926, u'name': u'trex-barrier'}}
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pharidos/work/tplaf/tplaf/node/tgn/trex.py", line 180, in stop_traffic
    self.stop_trex()
  File "/home/pharidos/work/tplaf/tplaf/node/tgn/trex.py", line 165, in stop_trex
    self.stop_trex_server()
  File "/home/pharidos/work/tplaf/tplaf/node/tgn/trex.py", line 127, in stop_trex_server
    if not self.is_trex_running():
  File "/home/pharidos/work/tplaf/tplaf/node/tgn/trex.py", line 117, in is_trex_running
    status = self.trex_server.is_running()
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 426, in is_running
    res = self.get_running_info()
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 549, in get_running_info
    self.result_obj.update_result_data(latest_dump)
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 1519, in update_result_data
    self._avg_latency        = CTRexResult.__avg_all_and_rename_keys(avg_latency)
  File "/home/pharidos/trex/trex_client_v2.34/stf/trex_stf_lib/trex_client.py", line 1602, in __avg_all_and_rename_keys
    all_list  = src_dict.values()
AttributeError: 'NoneType' object has no attribute 'values'
```
On pretty printing it, I see
```
{u'trex-barrier': {u'data': {}, u'name': u'trex-barrier', u'type': 2485789926},                                                                                                                                                     [80/4531]
 u'trex-event': {u'data': {u'port_id': 1,
                           u'session_id': 6557788,
                           u'who': u'pharidos'},
                 u'name': u'trex-event',
                 u'type': 6},
 u'trex-global': {u'data': {u'ibytes-0': 63771000,
                            u'ibytes-1': 63774132,
                            u'ierrors-0': 0,
                            u'ierrors-1': 0,
                            u'ipackets-0': 549750,
                            u'ipackets-1': 549777,
                            u'm_active_flows': 0.0,
                            u'm_active_sockets': 0,
                            u'm_bw_per_core': 2.393,
                            u'm_cpu_util': 2.64,
                            u'm_cpu_util-0': 0.0,
                            u'm_cpu_util-1': 0.0,
                            u'm_cpu_util_raw': 4.0,
                            u'm_open_flows': 0.0,
                            u'm_platform_factor': 1.0,
                            u'm_rx_bps': 53926956.0,
                            u'm_rx_core_pps': 58110.1,
                            u'm_rx_cpu_util': 0.2274,
                            u'm_rx_drop_bps': 0.0,
                            u'm_rx_pps': 58110.9,
                            u'm_socket_util': 0.0,
                            u'm_total_alloc_error': 0,
                            u'm_total_clients': 0,
                            u'm_total_nat_active': 0,
                            u'm_total_nat_learn_error': 0,
                            u'm_total_nat_no_fid': 0,
                            u'm_total_nat_open': 0,
                            u'm_total_nat_syn_wait': 0,
                            u'm_total_nat_time_out': 0,
                            u'm_total_nat_time_out_wait_ack': 0,
                            u'm_total_queue_drop': 0,
                            u'm_total_queue_full': 0,
                            u'm_total_rx_bps-0': 26964056.0,
                            u'm_total_rx_bps-1': 26962898.0,
                            u'm_total_rx_bytes': 127545132,
                            u'm_total_rx_pkts': 1099527,
                            u'm_total_rx_pps-0': 29056.1,
                            u'm_total_rx_pps-1': 29054.8,
                            u'm_total_servers': 0,
                            u'm_total_tx_bps-0': 15793666.0,
                            u'm_total_tx_bps-1': 15793917.0,
                            u'm_total_tx_bytes': 74767836,
                            u'm_total_tx_pkts': 1099527,
                            u'm_total_tx_pps-0': 29032.5,
                            u'm_total_tx_pps-1': 29032.9,
                            u'm_tx_bps': 31587582.0,
                            u'm_tx_cps': 0.0,
                            u'm_tx_expected_bps': 0.0,
                            u'm_tx_expected_cps': 0.0,
                            u'm_tx_expected_pps': 0.0,
                            u'm_tx_pps': 58065.4,
                            u'obytes-0': 37383000,
                            u'obytes-1': 37384836,
                            u'oerrors-0': 0,
                            u'oerrors-1': 0,      
                            u'opackets-0': 549750,
                            u'opackets-1': 549777,
                            u'template': [0,
                                          0,      
                                          0,      
                                          0,
                                          0,
                                          0,      
                                          0,      
                                          0,       
                                          0,       
                                          0,        
                                          0,    
                                          0,     
                                          0,     
                                          0,       
                                          0,     
                                          0,          
                                          0,        
                                          0,          
                                          0,         
                                          0,      
                                          0,     
                                          0,      
                                          0,          
                                          0,      
                                          0,         
                                          0,              
                                          0,         
                                          0,       
                                          0,           
                                          0,           
                                          0,                    
                                          0],        
                            u'ts': {u'freq': 2596991324,
                                    u'value': 425349401064},
                            u'unknown': 0},                 
                  u'name': u'trex-global',                 
                  u'type': 0},                          
 u'tx-gen': {u'data': {u'realtime-hist': {u'cnt': 0,     
                                          u'high_cnt': 0,
                                          u'histogram': [],
                                          u'max_usec': 0,   
                                          u'min_usec': 10,  
                                          u's_avg': 0.0}, 
                       u'unknown': 0},                  
             u'name': u'tx-gen',                         
             u'type': 0}}
```

**Comment by ybrustin** [comment]
Thanks, will be fixed in v2.36

**Comment by hprem** [comment]
Cool. Thanks :)

**Comment by hhaim** [comment]
fixed
