### ISSUE TITLE
Scapy server crashes after first request

### ISSUE THREAD

**Issue by EgorBlagov** [cisco-system-traffic-generator/trex-core#150]
Scapy server crashes (python2 and python3) after first request

```
trex@trex-ubuntu-home:~/trex-core/scripts/automation/trex_control_plane/interactive$ python -m trex.scapy_server.scapy_zmq_server -v
IGMPv3  is still under development - Nov 2010
/home/trex/trex-core/scripts/automation/trex_control_plane/interactive/trex/scapy_server/protocols.json
28-09-2018 14:12:51 ***Scapy Server Started***
28-09-2018 14:12:51 Listening on port: 4507
28-09-2018 14:12:51 Server IP address: 127.0.1.1
28-09-2018 14:13:05 Received Message: {"jsonrpc":"2.0","id":"1","method":"get_version"}
28-09-2018 14:13:05 Sending Message: {"jsonrpc": "2.0", "result": {"version": "1.02", "built_by": "itraviv"}, "id": "1"}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/trex/trex-core/scripts/automation/trex_control_plane/interactive/trex/scapy_server/scapy_zmq_server.py", line 194, in <module>
    sys.exit(main(args,port))
  File "/home/trex/trex-core/scripts/automation/trex_control_plane/interactive/trex/scapy_server/scapy_zmq_server.py", line 182, in main
    s.activate()
  File "/home/trex/trex-core/scripts/automation/trex_control_plane/interactive/trex/scapy_server/scapy_zmq_server.py", line 166, in activate
    self.socket.send_string(json_response)
AttributeError: 'Socket' object has no attribute 'send_string'
```

git bisect pointed on this commit as cause: https://github.com/cisco-system-traffic-generator/trex-core/commit/a93352ce117177c87ff8442e83c33e1da25ed784

**Comment by hhaim** [comment]
please try this fix. 
https://github.com/cisco-system-traffic-generator/trex-core/commit/706d02b06450c9689f2401edfa1540c043253a50
