### ISSUE TITLE
clear_tpg_stats won't compile in gcc8.1 +

### ISSUE THREAD

**Issue by bdollma** [cisco-system-traffic-generator/trex-core#815]
Starting from gcc8.1, performing `memset` on a non trivial type produces an error:

```
../../src/stx/common/trex_tpg_stats.cpp: In member function ‘void RxTPGPerPort::clear_tpg_stats(uint32_t, uint16_t, uint16_t, bool, bool)’:
../../src/stx/common/trex_tpg_stats.cpp:297:90: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class CTPGTagCntr’; use assignment or value-initialization instead [-Werror=class-memaccess]
         memset(get_tag_cntr(tpgid, min_tag), 0, sizeof(CTPGTagCntr) * (max_tag - min_tag));
```

https://github.com/cisco-system-traffic-generator/trex-core/blob/d92dad2ce5e97646ad22876dc1bd006141049771/src/stx/common/trex_tpg_stats.cpp#L297

should be replaced with something like this:

```c++
memset(static_cast<void*>get_tag_cntr(tpgid, min_tag), 0, sizeof(CTPGTagCntr) * (max_tag - min_tag));
```
