### ISSUE TITLE
compilation error due to failed static assertion

### ISSUE THREAD

**Issue by martin-weiser-allegro-packets** [cisco-system-traffic-generator/trex-core#21]
When compiling version v2.05 on Ubuntu 16.04 the compilation fails with the following output:

```
cd linux_dpdk/
./b configure
...
./b

...

[136/878] cxx: ../src/flow_stat.cpp -> build_dpdk/src/flow_stat.cpp.3.o
In file included from ../../src/trex_watchdog.cpp:22:0:
../../src/trex_watchdog.h:206:1: error: static assertion failed: sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE
 static_assert(sizeof(TrexMonitor) == RTE_CACHE_LINE_SIZE, "sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE" );
 ^
In file included from ../../src/bp_sim.h:61:0,
                 from ../../src/main_dpdk.h:21,
                 from ../../src/debug.cpp:30:
../../src/trex_watchdog.h:206:1: error: static assertion failed: sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE
 static_assert(sizeof(TrexMonitor) == RTE_CACHE_LINE_SIZE, "sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE" );
 ^
In file included from ../../src/bp_sim.h:61:0,
                 from ../../src/main_dpdk.cpp:54:
../../src/trex_watchdog.h:206:1: error: static assertion failed: sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE
 static_assert(sizeof(TrexMonitor) == RTE_CACHE_LINE_SIZE, "sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE" );
 ^
In file included from /mnt/hgfs/shared/trex-core/src/rpc-server/trex_rpc_server_api.h:33:0,
                 from /mnt/hgfs/shared/trex-core/src/stateless/cp/trex_stateless.h:32,
                 from ../../src/flow_stat.cpp:53:
/mnt/hgfs/shared/trex-core/src/trex_watchdog.h:206:1: error: static assertion failed: sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE
 static_assert(sizeof(TrexMonitor) == RTE_CACHE_LINE_SIZE, "sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE" );
 ^
Waf: Leaving directory `/mnt/hgfs/shared/trex-core/linux_dpdk/build_dpdk'
Build failed
...
```

The cpp used is 'cpp (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609' and the system is a 'Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz'.
It seems like the RTE_CACHE_LINE_SIZE is 64 but sizeof(TrexMonitor) is 128.
I could also reproduce this on a 'Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz' running an up to date Ubuntu 16.04.

**Comment by hhaim** [comment]
Hi, 
thanks for pointing out we will check this out.
Ubuntu 16.04.1 wasn't verify yet, Ubunto 14.01/Fedora 20-23 were verified  

thanks,
Hanoh

**Comment by hhaim** [comment]
You can mark this code, it is not required 

#static_assert(sizeof(TrexMonitor) == RTE_CACHE_LINE_SIZE, "sizeof(TrexMonitor) != RTE_CACHE_LINE_SIZE" );

however I'm not sure that everything will work on Ubunto 16 as we didn't test it
let's us know

**Comment by martin-weiser-allegro-packets** [comment]
With this code disabled trex compiles and seems to work fine on Ubuntu 16.04 (but I probably tested only a small subset of the features).
The watchdog also seems to work since it triggered e.g. when the links on the DUT went down and trex could not send any packets on the NICs.

**Comment by martin-weiser-allegro-packets** [comment]
Compilation on Ubuntu 16.04 is working with current master.
Thanks!
