### ISSUE TITLE
EAL: so/x86_64/libmlx5-64.so: undefined symbol: mlx5dv_query_devx_port

### ISSUE THREAD

**Issue by patrickrst** [cisco-system-traffic-generator/trex-core#968]
I tried to test the new release of TRex v3.01 which should work with OFED 5.7, but I am getting the following error. NIC is a ConnectX-5 and this same setup worked with an older version of TRex with RHEL 8.3 and OFED 5.3.

Any idea what could be wrong/missing for this setup to work?

```
$ sudo ./t-rex-64 -i
Error while determining OS type: module 'platform' has no attribute 'dist'
Starting Scapy server..... Scapy server is started
The ports are bound/configured.
Starting  TRex v3.01 please wait  ... 
EAL: so/x86_64/libmlx5-64.so: undefined symbol: mlx5dv_query_devx_port
EAL: FATAL: Cannot init plugins
EAL: Cannot init plugins
 You might need to run ./trex-cfg  once  
EAL: Error - exiting with code: 1
  Cause: Invalid EAL arguments
Killing Scapy server... Scapy server is killed
```

/etc/trex_cfg.yaml:
```
- version: 2
  port_limit: 2
  interfaces: ['2f:00.0', '2f:00.1']

  platform:
    master_thread_id: 0
    latency_thread_id: 17
    dual_if:
      - socket: 0
        threads: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
```

lspci:
```
2f:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
2f:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
```

Info:
- TRex v3.01
- RHEL 8.5
- Kernel 4.18.0-348.23.1.el8_5.x86_64
- MLNX_OFED_LINUX-5.7-1.0.2.0-rhel8.5-x86_64

**Comment by patrickrst** [comment]
Works with v3.02 !
